/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    Sqaure: (() => {
      const name = "Sqaure";
      return defineComponent(
        world,
        {
          square_id: RecsType.Number,
          square_creater: RecsType.String,
          square_description: RecsType.String,
          is_square_balance_add: RecsType.Boolean,
          square_balance: RecsType.Number,
          is_square_quest: RecsType.Boolean,
          square_quest_contract_address: RecsType.String,
          square_quest_description: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Player: (() => {
      const name = "Player";
      return defineComponent(
        world,
        {
          player_position: RecsType.Number,
          player_address: RecsType.String,
          player_balance: RecsType.Number,
          player_quest_status: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Map: (() => {
      const name = "Map";
      return defineComponent(
        world,
        {
          map_id: RecsType.Number,
          map_name: RecsType.String,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
